# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./audio_uploads:/app/audio_uploads
      - .:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=audio_service
      - YANDEX_REDIRECT_URI=your_yandex_redirect_uri
      - YANDEX_CLIENT_ID=your_yandex_client_id
      - YANDEX_CLIENT_SECRET=your_yandex_client_secret
      - JWT_SECRET=your_jwt_secret
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=30
      - AUDIO_UPLOAD_DIR=uploads/audio
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=audio_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  audio_uploads: